### PR TITLE
Add Ungoogled Chromium 96.0.4664.45

### LINKED ISSUE #31: update
thanks for your job it's amazing ❤️ 
 please update chromium portable more frequently currently latest version is 94 while the latest portable is 92

### PR DESCRIPTION
**Pull request by ghcontrib**
Add Ungoogled Chromium 95.0.4638.69

Fixes #31

### CODE REVIEW

**Comment by ghcontrib** [comment]
Hi @crazy-max 

Please review and merge this PR.
Let me know if something needs to be changed.

**Review by crazy-max — CHANGES_REQUESTED** [review]
Can you rebase and also remove changes from `CHANGELOG.md`? Thanks

**Comment by ghcontrib** [comment]
Rebased, removed changes in `CHANGELOG.md`, updated ungoogled chromium to version 96.0.4664.45

**Review by crazy-max — APPROVED** [review]
LGTM thanks!

**Pull request merged**
